### ISSUE TITLE
Compilation error on Ubuntu 18.04

### ISSUE THREAD

**Issue by jarun** [deadpixi/mtm#30]
Compilation fails on Ubuntu 18.04. Looks like `alloc_pair()` is introduced in ncurses 6.1.

```
$ make
cc -std=c99 -Wall -Wextra -pedantic -Os -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -o mtm  vtparser.c mtm.c  -lncursesw -lutil
mtm.c: In function ‘getinput’:
mtm.c:979:9: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
         read(statusfd, statusmsg, MAXOSC);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/cc4Dsw9O.o: In function `sgr':
mtm.c:(.text+0x19c5): undefined reference to `alloc_pair'
/tmp/cc4Dsw9O.o: In function `rc':
mtm.c:(.text+0x1b3e): undefined reference to `alloc_pair'
/tmp/cc4Dsw9O.o: In function `main':
mtm.c:(.text.startup+0x12e): undefined reference to `alloc_pair'
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'mtm' failed
make: *** [mtm] Error 1
```

**Comment by szabozoltan69** [comment]
For me the same.

$ make
cc -std=c99 -Wall -Wextra -pedantic -Os -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -o mtm  vtparser.c mtm.c  -lncursesw -lutil
/tmp/ccnurCA8.o: In function `sgr':
mtm.c:(.text+0x187c): undefined reference to `alloc_pair'
/tmp/ccnurCA8.o: In function `rc':
mtm.c:(.text+0x19f7): undefined reference to `alloc_pair'
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'mtm' failed
make: *** [mtm] Error 1

**Comment by fcpg** [comment]
It works on 19.04, fwiw.

**Comment by Asuza** [comment]
I was able to install ncurses 6.1 on Ubuntu 18.04 by following the instructions at https://www.osetc.com/en/how-to-install-ncurse-library-in-ubuntu-debian-centos-fedora-linux.html, however, I don't know how to build `mtm` using that specific library. If I can figure that out, it will hopefully compile.

**Comment by MichaelC2-718** [comment]
I have Ubuntu 18.04 and want to try mtm. Is this making any progress? Can I help?

**Comment by MichaelC2-718** [comment]
Never mind: I upgraded to Focal, and it compiles.

**Comment by jarun** [comment]
The following patch compiles it on 18.04 (but I don't see any colors):

```
diff --git a/mtm.c b/mtm.c
index 70011a2..c9c08e7 100644
--- a/mtm.c
+++ b/mtm.c
@@ -309,7 +309,12 @@ HANDLER(rc) /* RC - Restore Cursor */
     n->gc = n->sgc; n->gs = n->sgs;          /* save character sets        */
 
     /* restore colors */
+#if NCURSES_VERSION_PATCH <= 20180127
+    int cp = 1;
+    init_pair(cp, s->fg, s->bg);
+#else
     int cp = alloc_pair(s->fg, s->bg);
+#endif
     wcolor_set(win, cp, NULL);
     cchar_t c;
     setcchar(&c, L" ", A_NORMAL, cp, NULL);
@@ -330,7 +335,12 @@ ENDHANDLER
 
 HANDLER(el) /* EL - Erase in Line */
     cchar_t b;
+#if NCURSES_VERSION_PATCH <= 20180127
+    init_pair(1, s->fg, s->bg);
+    setcchar(&b, L" ", A_NORMAL, 1, NULL);
+#else
     setcchar(&b, L" ", A_NORMAL, alloc_pair(s->fg, s->bg), NULL);
+#endif
     switch (P0(0)){
         case 0: wclrtoeol(win);                                                 break;
         case 1: for (int i = 0; i <= x; i++) mvwadd_wchnstr(win, py, i, &b, 1); break;
@@ -359,7 +369,12 @@ ENDHANDLER
 
 HANDLER(ech) /* ECH - Erase Character */
     cchar_t c;
+#if NCURSES_VERSION_PATCH <= 20180127
+    init_pair(1, s->fg, s->bg);
+    setcchar(&c, L" ", A_NORMAL, 1, NULL);
+#else
     setcchar(&c, L" ", A_NORMAL, alloc_pair(s->fg, s->bg), NULL);
+#endif
     for (int i = 0; i < P1(0); i++)
         mvwadd_wchnstr(win, py, x + i, &c, 1);
     wmove(win, py, px);
@@ -506,7 +521,12 @@ HANDLER(sgr) /* SGR - Select Graphic Rendition */
         #endif
     }
     if (doc){
+#if NCURSES_VERSION_PATCH <= 20180127
+        int p = 1;
+        init_pair(p, s->fg = fg, s->bg = bg);
+#else
         int p = alloc_pair(s->fg = fg, s->bg = bg);
+#endif
         wcolor_set(win, p, NULL);
         cchar_t c;
         setcchar(&c, L" ", A_NORMAL, p, NULL);
```

**Comment by jarun** [comment]
Closing the defect with the above patch.
